name: bowtie-macs2
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - snakemake
    - trim-galore
    - fastqc
    - multiqc
    - bowtie
    - parallel-fastq-dump
    - macs2
